# Generated by Django 4.2.5 on 2023-10-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataInput", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="DataFile", new_name="DataInput",),
    ]
