# Generated by Django 4.2.5 on 2023-10-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataInput", "0004_datainput_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datainput",
            name="frequency",
            field=models.PositiveIntegerField(),
        ),
    ]
