# Generated by Django 4.2.5 on 2023-11-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataInput", "0005_alter_datainput_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datainput",
            name="frequency",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
