# Generated by Django 4.2.5 on 2023-10-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SessionParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("init_time_ms", models.PositiveIntegerField()),
                ("fin_time_ms", models.PositiveIntegerField()),
                ("frequency", models.PositiveIntegerField()),
            ],
            options={"abstract": False,},
        ),
    ]
